
import { Language } from "../types";

const DICTIONARY = {
  ID: {
    welcome: "Sistem Neuro-Link Terhubung.",
    startSystem: "MULAI SISTEM",
    aboutSystem: "DATA / ABOUT",
    connecting: "MENGHUBUNGKAN...",
    mainMenu: "MENU UTAMA",
    status: "STATUS",
    user: "PENGGUNA",
    online: "ONLINE",
    missionConfig: "KONFIGURASI MISI",
    turboMode: "⚡ TURBO",
    practiceMode: "🛡️ LATIHAN",
    selectModule: "PILIH MODUL",
    logout: "KELUAR",
    missionClear: "MISI SELESAI",
    totalScore: "TOTAL SKOR",
    accuracy: "AKURASI",
    aiAnalysis: "ANALISIS AI",
    processing: "MEMPROSES DATA...",
    menu: "MENU",
    retry: "ULANGI",
    settings: "PENGATURAN",
    bgm: "MUSIK",
    sfx: "EFEK SUARA",
    fontSize: "UKURAN FONT",
    saveExit: "SIMPAN & KELUAR",
    language: "BAHASA",
    quitTitle: "PERINGATAN SISTEM",
    quitConfirm: "Konfirmasi keluar? Data sesi ini akan hilang.",
    cancel: "BATAL",
    exit: "KELUAR",
    loading: "MEMUAT MODUL...",
    tutorialTitle: "CARA BERMAIN",
    ready: "SIAP, LAKSANAKAN!",
    about: {
      title: "DATABASE PENELITIAN",
      abstract: "ABSTRAK & TUJUAN",
      abstractText: "NeuroLatih dikembangkan berdasarkan prinsip 'Neuroplasticity'—kemampuan otak untuk memodifikasi koneksi saraf sebagai respons terhadap pengalaman baru. Tujuan aplikasi ini adalah menyediakan platform 'Gamified Cognitive Training' yang terstruktur untuk memelihara Kesehatan Kognitif dan meningkatkan Cognitive Reserve.",
      mapping: "PEMETAAN KORTEKS",
      output: "HARAPAN OUTPUT",
      outputText: "Latihan rutin ditargetkan untuk meningkatkan Fluid Intelligence (Gf), kecepatan pemrosesan informasi, dan efisiensi eksekutif. Aplikasi ini berfungsi sebagai alat pelengkap untuk menjaga ketajaman mental di era digital.",
      references: "REFERENSI / BASIS ILMIAH",
      back: "KEMBALI"
    },
    pathfinding: {
      title: "PEMROGRAMAN BOT",
      loadMission: "MEMUAT MISI...",
      missionSelect: "PILIH MISI",
      resume: "LANJUTKAN MISI",
      save: "SIMPAN",
      clear: "HAPUS",
      undo: "UNDO",
      execute: "EKSEKUSI",
      running: "BERJALAN...",
      programBot: "PROGRAM BOT",
      commands: "PERINTAH",
      debug: "DEBUG",
      goal: "CAPAI BENDERA",
      avoidWalls: "HINDARI TEMBOK",
      tutorialTitle: "CARA BERMAIN",
      missions: {
        random: "ACAK (Klasik)",
        labyrinth: "LABIRIN (DFS)",
        bunker: "BUNKER (Spiral)",
        binary: "BINARY (Bias)",
        obstacle: "RINTANGAN (Chaos)"
      }
    }
  },
  EN: {
    welcome: "Neuro-Link System Connected.",
    startSystem: "START SYSTEM",
    aboutSystem: "DATA / ABOUT",
    connecting: "CONNECTING...",
    mainMenu: "MAIN MENU",
    status: "STATUS",
    user: "USER",
    online: "ONLINE",
    missionConfig: "MISSION CONFIG",
    turboMode: "⚡ TURBO",
    practiceMode: "🛡️ PRACTICE",
    selectModule: "SELECT MODULE",
    logout: "LOGOUT",
    missionClear: "MISSION CLEARED",
    totalScore: "TOTAL SCORE",
    accuracy: "ACCURACY",
    aiAnalysis: "AI ANALYSIS",
    processing: "PROCESSING DATA...",
    menu: "MENU",
    retry: "RETRY",
    settings: "SETTINGS",
    bgm: "MUSIC",
    sfx: "SFX",
    fontSize: "FONT SIZE",
    saveExit: "SAVE & EXIT",
    language: "LANGUAGE",
    quitTitle: "SYSTEM ALERT",
    quitConfirm: "Confirm exit? Session data will be lost.",
    cancel: "CANCEL",
    exit: "EXIT",
    loading: "LOADING MODULE...",
    tutorialTitle: "HOW TO PLAY",
    ready: "READY, EXECUTE!",
    about: {
      title: "RESEARCH DATABASE",
      abstract: "ABSTRACT & OBJECTIVE",
      abstractText: "NeuroLatih is developed based on 'Neuroplasticity' principles—the brain's ability to reorganize itself by forming new neural connections. The goal is to provide structured 'Gamified Cognitive Training' to maintain Cognitive Health and enhance Cognitive Reserve.",
      mapping: "CORTICAL MAPPING",
      output: "EXPECTED OUTCOME",
      outputText: "Routine training targets improvements in Fluid Intelligence (Gf), information processing speed, and executive efficiency. This app serves as a supplementary tool to maintain mental sharpness in the digital age.",
      references: "REFERENCES / SCIENTIFIC BASIS",
      back: "RETURN"
    },
    pathfinding: {
      title: "BOT PROGRAMMING",
      loadMission: "LOADING MISSION...",
      missionSelect: "SELECT MISSION",
      resume: "RESUME MISSION",
      save: "SAVE",
      clear: "CLEAR",
      undo: "UNDO",
      execute: "EXECUTE",
      running: "RUNNING...",
      programBot: "PROGRAM BOT",
      commands: "COMMANDS",
      debug: "DEBUG",
      goal: "REACH THE FLAG",
      avoidWalls: "AVOID WALLS",
      tutorialTitle: "HOW TO PLAY",
      missions: {
        random: "RANDOM (Classic)",
        labyrinth: "THE LABYRINTH (DFS)",
        bunker: "THE BUNKER (Spiral)",
        binary: "BINARY RUN (Bias)",
        obstacle: "OBSTACLE (Chaos)"
      }
    }
  }
};

export const getTranslation = (lang: Language, key: string) => {
  return key.split('.').reduce((o, i) => (o as any)?.[i], DICTIONARY[lang]) || key;
};