
import { Language } from "../types";

const DICTIONARY = {
  ID: {
    welcome: "NEURAL-LINK SYSTEM: ONLINE.",
    startSystem: ">> EXECUTE PROTOCOL",
    aboutSystem: "SYSTEM KERNEL / DATA",
    connecting: "ESTABLISHING UPLINK...",
    mainMenu: "COMMAND CENTER",
    status: "SYSTEM STATUS",
    user: "OPERATOR",
    online: "CONNECTED",
    missionConfig: "SYSTEM CONFIGURATION",
    turboMode: "⚡ OVERCLOCK",
    practiceMode: "🛡️ SIMULATION",
    selectModule: "SELECT NEURAL MODULE",
    logout: "DISCONNECT",
    missionClear: "MISSION ACCOMPLISHED",
    totalScore: "PERFORMANCE RATING",
    accuracy: "SYNAPTIC ACCURACY",
    aiAnalysis: "AI DIAGNOSTIC",
    processing: "ANALYZING PATTERNS...",
    menu: "DASHBOARD",
    retry: "RE-INITIALIZE",
    settings: "SYSTEM PREFERENCES",
    bgm: "AUDIO STREAM",
    sfx: "HAPTIC FEEDBACK",
    fontSize: "INTERFACE SCALE",
    saveExit: "COMMIT & EXIT",
    language: "LANGUAGE PACK",
    theme: "VISUAL MODE",
    dark: "VOID",
    light: "SOLAR",
    quitTitle: "TERMINATION SIGNAL",
    quitConfirm: "Putuskan koneksi neural? Data sesi yang belum tersimpan akan hilang.",
    cancel: "RESUME",
    exit: "TERMINATE",
    loading: "LOADING ASSETS...",
    tutorialTitle: "PROTOCOL MANUAL",
    ready: "LINK ESTABLISHED!",
    stats: {
      title: "NEURO-METRIC PROFILER",
      subtitle: "ANALISIS ATRIBUT KOGNITIF",
      memory: "MEMORY",
      logic: "LOGIC",
      speed: "SPEED",
      focus: "FOCUS",
      verbal: "VERBAL",
      archetype: "NEURAL ARCHETYPE",
      balanced: "BALANCED MIND"
    },
    about: {
      title: "CENTRAL DATABASE",
      abstract: "CORE ARCHITECTURE",
      abstractText: "NeuroLatih dirancang sebagai 'Cognitive Enhancement Suite' berbasis neuroplastisitas. Sistem ini merekayasa ulang jalur saraf melalui tantangan gamifikasi terstruktur, meningkatkan bandwidth pemrosesan mental dan efisiensi eksekutif.",
      mapping: "CORTICAL MAPPING",
      output: "PROJECTED OUTPUT",
      outputText: "Eksekusi rutin meningkatkan Fluid Intelligence (Gf), latensi pemrosesan data, dan kapasitas memori kerja. Anggap ini sebagai 'Software Update' untuk hardware biologis Anda.",
      references: "SOURCE CODE / REFERENCES",
      back: "RETURN TO ROOT"
    },
    pathfinding: {
      title: "BOT ALGORITHM",
      loadMission: "LOADING MAP...",
      missionSelect: "SELECT SECTOR",
      resume: "RESUME OPERATION",
      save: "SAVE STATE",
      clear: "FLUSH MEMORY",
      undo: "REVERT STEP",
      execute: "RUN SEQUENCE",
      running: "EXECUTING...",
      programBot: "PROGRAM SEQUENCE",
      commands: "INSTRUCTION SET",
      debug: "DEBUG MODE",
      goal: "ACQUIRE TARGET",
      avoidWalls: "AVOID COLLISION",
      tutorialTitle: "OPERATIONAL GUIDE",
      missions: {
        random: "SECTOR: RANDOM",
        labyrinth: "SECTOR: LABYRINTH",
        bunker: "SECTOR: BUNKER",
        binary: "SECTOR: BINARY",
        obstacle: "SECTOR: HAZARD"
      }
    }
  },
  EN: {
    welcome: "NEURAL-LINK SYSTEM: ONLINE.",
    startSystem: ">> EXECUTE PROTOCOL",
    aboutSystem: "SYSTEM KERNEL / DATA",
    connecting: "ESTABLISHING UPLINK...",
    mainMenu: "COMMAND CENTER",
    status: "SYSTEM STATUS",
    user: "OPERATOR",
    online: "CONNECTED",
    missionConfig: "SYSTEM CONFIGURATION",
    turboMode: "⚡ OVERCLOCK",
    practiceMode: "🛡️ SIMULATION",
    selectModule: "SELECT NEURAL MODULE",
    logout: "DISCONNECT",
    missionClear: "MISSION ACCOMPLISHED",
    totalScore: "PERFORMANCE RATING",
    accuracy: "SYNAPTIC ACCURACY",
    aiAnalysis: "AI DIAGNOSTIC",
    processing: "ANALYZING PATTERNS...",
    menu: "DASHBOARD",
    retry: "RE-INITIALIZE",
    settings: "SYSTEM PREFERENCES",
    bgm: "AUDIO STREAM",
    sfx: "HAPTIC FEEDBACK",
    fontSize: "INTERFACE SCALE",
    saveExit: "COMMIT & EXIT",
    language: "LANGUAGE PACK",
    theme: "VISUAL MODE",
    dark: "VOID",
    light: "SOLAR",
    quitTitle: "TERMINATION SIGNAL",
    quitConfirm: "Sever neural connection? Unsaved session data will be purged.",
    cancel: "RESUME",
    exit: "TERMINATE",
    loading: "LOADING ASSETS...",
    tutorialTitle: "PROTOCOL MANUAL",
    ready: "LINK ESTABLISHED!",
    stats: {
      title: "NEURO-METRIC PROFILER",
      subtitle: "COGNITIVE ATTRIBUTE ANALYSIS",
      memory: "MEMORY",
      logic: "LOGIC",
      speed: "SPEED",
      focus: "FOCUS",
      verbal: "VERBAL",
      archetype: "NEURAL ARCHETYPE",
      balanced: "BALANCED MIND"
    },
    about: {
      title: "CENTRAL DATABASE",
      abstract: "CORE ARCHITECTURE",
      abstractText: "NeuroLatih is designed as a neuroplasticity-based 'Cognitive Enhancement Suite'. The system re-engineers neural pathways through structured gamified challenges, increasing mental processing bandwidth and executive efficiency.",
      mapping: "CORTICAL MAPPING",
      output: "PROJECTED OUTPUT",
      outputText: "Routine execution enhances Fluid Intelligence (Gf), data processing latency, and working memory capacity. Consider this a 'Software Update' for your biological hardware.",
      references: "SOURCE CODE / REFERENCES",
      back: "RETURN TO ROOT"
    },
    pathfinding: {
      title: "BOT ALGORITHM",
      loadMission: "LOADING MAP...",
      missionSelect: "SELECT SECTOR",
      resume: "RESUME OPERATION",
      save: "SAVE STATE",
      clear: "FLUSH MEMORY",
      undo: "REVERT STEP",
      execute: "RUN SEQUENCE",
      running: "EXECUTING...",
      programBot: "PROGRAM SEQUENCE",
      commands: "INSTRUCTION SET",
      debug: "DEBUG MODE",
      goal: "ACQUIRE TARGET",
      avoidWalls: "AVOID COLLISION",
      tutorialTitle: "OPERATIONAL GUIDE",
      missions: {
        random: "SECTOR: RANDOM",
        labyrinth: "SECTOR: LABYRINTH",
        bunker: "SECTOR: BUNKER",
        binary: "SECTOR: BINARY",
        obstacle: "SECTOR: HAZARD"
      }
    }
  }
};

export const getTranslation = (lang: Language, key: string) => {
  return key.split('.').reduce((o, i) => (o as any)?.[i], DICTIONARY[lang]) || key;
};
